In [1]:
import pandas as pd

In [13]:
MARKER_FILE_PATH = r"D:\000_data_collection_hti\girish-demo-clippong-markers.csv"
df = pd.read_csv(MARKER_FILE_PATH)

In [14]:
df

                 start_time        next_question_time
0  2026-06-11T07:00:39.171Z  2026-06-11T07:00:44.629Z
1                       NaN  2026-06-11T07:00:48.967Z
2                       NaN  2026-06-11T07:00:52.490Z
3                       NaN  2026-06-11T07:00:57.867Z
4                       NaN  2026-06-11T07:01:02.820Z
5                       NaN  2026-06-11T07:01:06.724Z
6                       NaN  2026-06-11T07:01:11.247Z
7                       NaN  2026-06-11T07:01:15.989Z
8                       NaN  2026-06-11T07:01:19.002Z
9                       NaN  2026-06-11T07:01:24.773Z

In [15]:
# Copy all rows except last from column B
# into column A starting from row 2
df.loc[1:, "start_time"] = df["next_question_time"].iloc[:-1].values

df

                 start_time        next_question_time
0  2026-06-11T07:00:39.171Z  2026-06-11T07:00:44.629Z
1  2026-06-11T07:00:44.629Z  2026-06-11T07:00:48.967Z
2  2026-06-11T07:00:48.967Z  2026-06-11T07:00:52.490Z
3  2026-06-11T07:00:52.490Z  2026-06-11T07:00:57.867Z
4  2026-06-11T07:00:57.867Z  2026-06-11T07:01:02.820Z
5  2026-06-11T07:01:02.820Z  2026-06-11T07:01:06.724Z
6  2026-06-11T07:01:06.724Z  2026-06-11T07:01:11.247Z
7  2026-06-11T07:01:11.247Z  2026-06-11T07:01:15.989Z
8  2026-06-11T07:01:15.989Z  2026-06-11T07:01:19.002Z
9  2026-06-11T07:01:19.002Z  2026-06-11T07:01:24.773Z

In [16]:
# Convert columns to datetime
df["start_time"] = pd.to_datetime(df["start_time"])
df["next_question_time"] = pd.to_datetime(df["next_question_time"])

# Add duration column (seconds)
df["duration_sec"] = (
    df["next_question_time"] - df["start_time"]
).dt.total_seconds()
df

,start_time,next_question_time,duration_sec
0,2026-06-11 07:00:39.171000+00:00,2026-06-11 07:00:44.629000+00:00,5.458
1,2026-06-11 07:00:44.629000+00:00,2026-06-11 07:00:48.967000+00:00,4.338
2,2026-06-11 07:00:48.967000+00:00,2026-06-11 07:00:52.490000+00:00,3.523
3,2026-06-11 07:00:52.490000+00:00,2026-06-11 07:00:57.867000+00:00,5.377
4,2026-06-11 07:00:57.867000+00:00,2026-06-11 07:01:02.820000+00:00,4.953
5,2026-06-11 07:01:02.820000+00:00,2026-06-11 07:01:06.724000+00:00,3.904
6,2026-06-11 07:01:06.724000+00:00,2026-06-11 07:01:11.247000+00:00,4.523
7,2026-06-11 07:01:11.247000+00:00,2026-06-11 07:01:15.989000+00:00,4.742
8,2026-06-11 07:01:15.989000+00:00,2026-06-11 07:01:19.002000+00:00,3.013
9,2026-06-11 07:01:19.002000+00:00,2026-06-11 07:01:24.773000+00:00,5.771